### ISSUE TITLE
Research: Update Related People & Groups HAL Link to include People who produced or encountered objects in a collection sets curated by the department/group.

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#101]
**Problem Description:**
Search for:

Person -> Created Or Encountered Object -> Member Of a Set -> Curated By this Department

**Expected Behavior/Solution:**
- Include a search which pulls all related people who produced or encountered objects in collection sets curated by this departmental group. 
- TBD based on research to determine how to create this search to update the existing HAL link. 

**Requirements:**
- the HAL Link [HAL Link Query Name] in the `Related People and Groups` accordion will be updated to include related people who produced or encountered objects in collection sets curated by this departmental group. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux.collections.yale.edu/view/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- https://www.bugherd.com/projects/284041/tasks/2600

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
@clarkepeterf 
moving this to priority review, so you can begin research on how to update the HAL link. 
Also - what is the HAL link for the related people and groups accordion?

**Comment by clarkepeterf** [comment]
@azaroth42 if we don't want the inverse relationship, we have the ability to exclude relationships we don't want from related lists.

If only the proposed relationship and not the inverse is preferable, let me know.

If we don't want to expose either relationship, that is fine too.

**Comment by roamye** [comment]
@clarkepeterf from UAT 10/10
- closing as even if it is possible for some, this issue will be computational expensive.

**Comment by roamye** [comment]
closing
