### ISSUE TITLE
Create HAL Link For Archive's Item's With Digital Images (from 119)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#14]
**Problem Description:**
A HAL Link is needed to Show Items in an Archive that have digital images

**Expected Behavior/Solution:**
Archive pages receive HAL Links for Items in the set with digitial images (nested up to 3 levels deep)

**Requirements:**
The hal link should look like this:
```
{
    "AND": [
        {
            "OR": [
                {
                    "memberOf": {
                        "id": "${ARCHIVE_ID}"
                    }
                },
                {
                    "memberOf": {
                        "member": {
                            "id": "${ARCHIVE_ID}"
                        }
                    }
                },
                {
                    "memberOf": {
                        "member": {
                            "memberOf": {
                                "id": "${ARCHIVE_ID}"
                            }
                        }
                    }
                }
            ]
        },
        {
            "hasDigitalImage": 1
        }
    ]
}
```

Example HAL Link:

```
"lux:setItemsWithImages": {
"href": "https://lux-front-tst.collections.yale.edu/api/search?q=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fset%2F04693629-c245-4fa9-ba8f-4d6c7ddf1920%22%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fset%2F04693629-c245-4fa9-ba8f-4d6c7ddf1920%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fset%2F04693629-c245-4fa9-ba8f-4d6c7ddf1920%22%7D%7D%7D%7D%5D%7D%2C%7B%22hasDigitalImage%22%3A1%7D%5D%7D&scope=item",
"_estimate": 1
},
```
**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
- [ ] Frontend item: https://git.yale.edu/lux-its/lux-web/issues/1728 | https://github.com/project-lux/lux-frontend/issues/28
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

Example HAL Link:

```
"lux:setItemsWithImages": {
"href": "https://lux-front-tst.collections.yale.edu/api/search?q=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fset%2F04693629-c245-4fa9-ba8f-4d6c7ddf1920%22%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fset%2F04693629-c245-4fa9-ba8f-4d6c7ddf1920%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fset%2F04693629-c245-4fa9-ba8f-4d6c7ddf1920%22%7D%7D%7D%7D%5D%7D%2C%7B%22hasDigitalImage%22%3A1%7D%5D%7D&scope=item",
"_estimate": 1
},
```

~~**Dependencies/Blocks:**~~

~~**Related Github Issues:**~~

~~**Related links:**~~

~~**Wireframe/Mockup:**~~

**Comment by roamye** [comment]
@kamerynB should the status be Reviewable?

**Comment by kamerynB** [comment]
@roamye It hasn't been deployed yet. The deployment is happening later today.

**Comment by roamye** [comment]
@kamerynB gotcha, pls ignore my dupe comments on the other issues. Thanks!

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in json prod. Closing

**Comment by brent-hartwig** [comment]
@jffcamp and @prowns, a /searchWillMatch request in production (Green) timed out after 20 seconds in yesterday.  If I tracked the code correctly, the query is the one implemented for this ticket.  It checks three semantic hops (1 level and 2 levels and 3 levels away from the item) and thus I'm not surprised it could fail for a set with many items.  In this particular case, the set was that of "Offsite Storage, Yale University Library".  The DEV link is https://lux-front-dev.collections.yale.edu/view/set/4b2b3586-7eaf-4b47-9af5-476e41a5f38c (2024-05-29 dataset).  Could be just an FYI.  Also note transitive triple support in Optic could be faster (and does not require we specify how many levels to check.

Query from middle tier:

```json
{
  "criteria": {
    "AND": [
      {
        "OR": [
          {
            "memberOf": {
              "id": "https://lux.collections.yale.edu/data/set/4b2b3586-7eaf-4b47-9af5-476e41a5f38c"
            }
          },
          {
            "memberOf": {
              "memberOf": {
                "id": "https://lux.collections.yale.edu/data/set/4b2b3586-7eaf-4b47-9af5-476e41a5f38c"
              }
            }
          },
          {
            "memberOf": {
              "memberOf": {
                "memberOf": {
                  "id": "https://lux.collections.yale.edu/data/set/4b2b3586-7eaf-4b47-9af5-476e41a5f38c"
                }
              }
            }
          }
        ]
      },
      { "hasDigitalImage": 1 }
    ]
  }
}
```

cc: @clarkepeterf, @roamye

**Comment by roamye** [comment]
@brent-hartwig to your question - I am not sure (I know, not helpful). What I do know is that #77 (update of the HAL link of this issue) no longer loads slowly in TST and will be deployed in PROD next Monday.

**Comment by brent-hartwig** [comment]
Good deal, @roamye.  We can wait to see if additional such alerts come in after #77 reaches PROD.  Thank you.
