### ISSUE TITLE
Remove workShownBy HAL Link (from 120)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#15]
**Problem Description:**
the workShownBy HAL Link is a duplicate of the workCarriedBy HAL Link

**Expected Behavior/Solution:**
workShownBy is removed, workCarriedBy behaves the same as current
**Requirements:**
Remove the workShownBy HAL Link. This will require that the frontend changes any pages that use workShownBy to use workCarriedBy instead

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
- [ ] Frontend ticket from @kl762 
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/data/text/6aaa7701-02e7-4249-9bf5-faf1edc2c652

~~**Dependencies/Blocks:**~~

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/277

~~**Related links:**~~

~~**Wireframe/Mockup:**~~

**Comment by roamye** [comment]
@kamerynB - what is the FE ticket for this? and is there a UAT link where I can see the worksShownBy hal link is removed from the JSON?

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod. Closing.
