### ISSUE TITLE
HAL Link - Agent Founded By Agent (from 123) - frontend 74

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#16]
**Problem Description:**
We need a HAL link for agents foundedBy an agent for https://github.com/project-lux/lux-frontend/issues/74

**Expected Behavior/Solution:**
Create a new HAL link that returns a list of organizations founded by a person/group

**Requirements:**

Search criteria:

```
// Find agents who died at the place.
const agentsFoundedByAgent = (agentId) => ({
  _scope: 'agent',
  foundedBy: {
    id: agentId,
  },
})

module.exports = agentsFoundedByAgent

```

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**
Example link:

```
"lux:agentFoundedByAgent": {
"href": "https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22foundedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fperson%2Feca91692-995a-43e5-95eb-ea5a668c16bc%22%7D%7D",
"_estimate": 1
},
```

~~**Dependencies/Blocks:**~~

**Related Github Issues:**
Required for [ Add accordion for groups founded (from 1992) #74](https://github.com/project-lux/lux-frontend/issues/74)

~~**Related links:**~~

~~**Wireframe/Mockup:**~~

**Comment by clarkepeterf** [comment]
@prowns should the list of agents be sorted?

**Comment by prowns** [comment]
@kamerynB and @clarkepeterf - what is the current protocol for sorting accordion results?  Why would this be any different?

**Comment by kamerynB** [comment]
@prowns The sorting of results is done by adding the parameter `sort=<sort direction>:<term to sort on>` to the HAL link. The frontend can't sort results as we limit 20 results per search. The frontend would have inconsistent sorting.

**Comment by roamye** [comment]
@clarkepeterf does the status need to be updated or is this tix still in progress? if so I will move to next deployment schedule.

**Comment by kamerynB** [comment]
Update 4/8/24:
There is an issue in the data where IDs are not being returned for /formed_by/carried_out_by.

![Screenshot 2024-04-08 at 12 03 26 PM](https://github.com/project-lux/lux-middletier/assets/140102078/a1544382-427b-4c39-9b23-9415c8d1306f)

**Comment by roamye** [comment]
uat json example appears in the prod json. good to close.
