### ISSUE TITLE
Remove data constants endpoint

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#18]
**Problem Description:**
Data constants are going to be replaced by AATs which will be managed by the frontend.

**Expected Behavior/Solution:**
The data-constants endpoint can be removed once the frontend is not dependent on it.

**Requirements:**
- [x] Remove the `/api/data-constants` endpoint 

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/api/data-constants (TST) 
- https://lux.collections.yale.edu/api/data-constants (PRD) 

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-marklogic/issues/54
- Blocked By: https://github.com/project-lux/lux-frontend/issues/196

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by kamerynB** [comment]
@roamye This is going to be repurposed. The endpoint to retrieve data constants can be removed from the middle tier.

**Comment by roamye** [comment]
@kamerynB - is there any UAT links for this? Or are all records supposed to contain working as it has previously?

**Comment by kamerynB** [comment]
@roamye There are no UAT links for the frontend. This was done once the AAT issue was completed as data constants are no longer required. You can hit the [middle tier directly here](https://lux-front-tst.collections.yale.edu/api/data-constants) and see that the link no longer works.

**Comment by roamye** [comment]
Approved by UAT 8/7

**Comment by roamye** [comment]
Looks good in PROD. Closing.
