### ISSUE TITLE
HAL Link: Related List for People Active Here - frontend 34

### ISSUE THREAD

**Issue by jffcamp** [project-lux/lux-middletier#19]
**Problem Description:**
Add a related list for People Active Here to support https://github.com/project-lux/lux-frontend/issues/34

**Expected Behavior/Solution:**
This ticket will provide a HAL Link that will support a new accordion for People Active Here

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- ~~[ ] Wireframe/Mockup - Mike~~
- ~~[ ] Committee discussions - Sarah~~
- ~~[ ] Feasibility/Team discussion - Sarah~~
- [x] Backend requirements - This query: https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22activeAt%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fplace%2Fd8c3e262-187a-40f3-843f-cf618aefde4a%22%7D%7D
- [x] Frontend requirements- https://github.com/project-lux/lux-frontend/issues/34
- ~~[ ] Questions~~
- ~~List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- Tested from the [front-end](https://github.com/project-lux/lux-frontend/issues/34) ticket

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-frontend/issues/34

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by kamerynB** [comment]
@clarkepeterf This is one that I can tackle but am unsure if there is ML support.

**Comment by prowns** [comment]
deployed

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod, closing
