### ISSUE TITLE
Align API call timeout w/ upstream (from 13)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#2]
**Problem Description:**
[from Team mtg, 11/17/23](https://docs.google.com/document/d/1WDEhu_epL-KVjvp9Ck_8cEfHTCpw9j3HdxYZwwnq-60/edit): Middle tier and backend need the same timeouts

**Expected Behavior/Solution:**
Configure the middle tier and backend to have the same timeouts. 

**Requirements:**
N/A TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Seong + Peter to clarify and form ticket
- [ ] Reach out to Brent to clarify
- [ ] Important to understand and document in ticket
- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
TBD

**Dependencies/Blocks:**
- Dependent on: ML Support Issue.

**Related Github Issues:**
-  https://git.yale.edu/lux-its/marklogic/issues/498

**Related links:**
ML Support Ticket: 

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Old ticket (https://git.yale.edu/lux-its/lux-backend/issues/13): 
Based on the conversation of the old tix this ticket needed to be clarified and formed. However, is this ticket still relevant? 

@gigamorph

**Comment by roamye** [comment]
tix forming 6/17: 
Not fixable in middle-tier because it is an issue related to the node library.
Implement a rest call for time outs..

@gigamorph  Seong will do some more research and open a ML support tix. Please add it to this issue once it is opened.

**Comment by roamye** [comment]
@gigamorph - was the ML support tix created?

**Comment by roamye** [comment]
TF 11/20: 
We do not have control over aligning. Unsure if there is a corresponding mark logic ticket.
 
@brent-hartwig - is this ticket still needed?

**Comment by brent-hartwig** [comment]
@roamye, I don't know of a current need or situation whereby we need middle tier timeout adjustments.  I'm good with closing this until a need arises.

**Comment by roamye** [comment]
UAT closing.
