### ISSUE TITLE
Create HAL link for Place With Type - frontend 107

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#21]
**Problem Description:**
Concept pages need a HAL link  for places with that type to support https://github.com/project-lux/lux-frontend/issues/107

**Expected Behavior/Solution:**
HAL link exists to show places with a type

**Requirements:**

- [x] Add config for the HAL link

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

When visiting this page:
https://lux-front-tst.collections.yale.edu/view/concept/ce2af8c9-1d34-46be-a3cb-434f332d678b

A hal link should return the following search:
https://lux-front-tst.collections.yale.edu/api/search/place?q=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Fce2af8c9-1d34-46be-a3cb-434f332d678b%22%7D%7D%5D%7D&page=1&sort=

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-frontend/issues/107

**Related Github Issues:**
https://github.com/project-lux/lux-frontend/issues/107

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1888
**Wireframe/Mockup:**

**Comment by prowns** [comment]
@ar2674 - this should be updated following decisions on https://github.com/project-lux/lux-frontend/issues/107

**Comment by roamye** [comment]
@kamerynB "when visiting this page" in requirements and UAT links section have URLs of records of "Nation" and "War of Independence, 1820-1829".  Nations shows Places with Type while War of Independence does not. Should both of them show this accordion? or were both links supposed to redirect to Nations and not War of Independence?

**Comment by kamerynB** [comment]
@roamye I updated the original comment. Looks like "Nations" should be the main example. "War of Independence" does not have this relationship.

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod closing
