### ISSUE TITLE
Create Related Subjects HAL Links

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#24]
**Problem Description:**
The frontend wants to display related subjects on events. This should be a faceted list. At the moment it does not show the "show all" results on the right hand side of the faceted types. The query needs to be updated to include this. 

**Expected Behavior/Solution:**
HAL Links exist that return related subjects for:
- Exhibitions
- Periods

- it should also include the "show all" on the right hand side. Refer to wireframe in [front-end](https://github.com/project-lux/lux-frontend/issues/7).
**Requirements:**
Exampe of subjects for an exhibition:
https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22subjectOfConcept%22%3A%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22usedForEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6e09857c-6b08-4155-a3b9-c7055d688d92%22%7D%7D%7D%7D%7D

Example of subjects for a period:
https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22influencedByEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6297d4d4-ea61-45b2-8c47-9a0e6298fdcc%22%7D%7D

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

This page (https://lux-front-tst.collections.yale.edu/view/activity/6297d4d4-ea61-45b2-8c47-9a0e6298fdcc) would show an accordion whose results are from this search:  https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22influencedByEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6297d4d4-ea61-45b2-8c47-9a0e6298fdcc%22%7D%7D
Using a HAL link called "lux:eventConceptsInfluecedBy"

This page (https://lux-front-tst.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92) would show an accordion based on this search:
https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22subjectOfConcept%22%3A%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22usedForEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6e09857c-6b08-4155-a3b9-c7055d688d92%22%7D%7D%7D%7D%7D
Using a HAL link called "lux:eventConceptsOfItems"

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-frontend/issues/7

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by brent-hartwig** [comment]
@kamerynB, the middle tier has queries for these.  Use `conceptsSubjectsForExhibition` for exhibition and `conceptsSubjectsForPeriod` for period.  Is that what you're looking for?

**Comment by clarkepeterf** [comment]
@jffcamp @prowns @azaroth42 
This ticket says the lists should be faceted lists, but there are two different relationships, only one of which I think could be a faceted list.

First, there is a relationship for Periods:
 - https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22influencedByEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6297d4d4-ea61-45b2-8c47-9a0e6298fdcc%22%7D%7D
 - The Event is a direct influence of the Concept. Since there is not a 3rd entity to search through, I don't think this can be a facet. It just needs to be a search.
 
Second, there is the relationship for Exhibitions:
- https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22subjectOfConcept%22%3A%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22usedForEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6e09857c-6b08-4155-a3b9-c7055d688d92%22%7D%7D%7D%7D%7D
- This could make sense as a facet. We could do a search for the Works carried by Objects used in the Event, and then facet those Works by subject (Concept that the Work is about). I just want to make sure that's what we want.

**Comment by prowns** [comment]
@clarkepeterf - They are different, so what is needed to match the mockups on https://github.com/project-lux/lux-frontend/issues/7 ?

cc; @roamye

**Comment by roamye** [comment]
@clarkepeterf can this issue still be deployed for 04-01 or will we need more time & have to move it to 04-15?

**Comment by azaroth42** [comment]
These issues are a mess!

lux-frontend#7 is for a related lists accordion, but the mockups show a search and a facets, not a related list. 

#agenda

**Comment by clarkepeterf** [comment]
Rather than "related subjects", I believe the first query should be called "Concepts Influenced" - and would not be a related list.

The second query could be part of a related list, or could be implemented as a faceted search.

But I agree, we should add this to the agenda and discuss at the team meeting

**Comment by roamye** [comment]
closing per 5/4 team meeting.
