### ISSUE TITLE
Add HAL link for Objects Influenced by a Person

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-middletier#27]
**Problem Description:**
The person page is missing data related to objects they have influenced.

**Expected Behavior/Solution:**
Existing HAL links for Objects Created/Encountered and for Works Created/Published should have Influenced By added

**Requirements:**
- The following tabs will exist with the creation of the HAL link: 
"Objects Created or Encountered or Influenced By" and "Works Created, Published, or Influenced By"

- [x] ML query - @clarkepeterf (https://github.com/project-lux/lux-marklogic/issues/65)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- ~[ ] Backend requirements - TBD~
- ~[ ] Frontend requirements- TBD~
- [x] QA regresstion test | Amy | No, this will be captured in Peters Hal Link generation. 
- ~[ ] Questions~
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/person/0573429b-32ef-4a42-99e6-fd4b382d7e8e
- https://lux-front-tst.collections.yale.edu/view/person/bf461170-26c9-4c95-b72e-63fdd47a8746 (Works created, published, or influenced by) 

**Dependencies/Blocks:**

Blocked by: https://github.com/project-lux/lux-marklogic/issues/65
Blocking: https://github.com/project-lux/lux-frontend/issues/87

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/87

**Related links:**

- https://www.bugherd.com/projects/284041/tasks/1943

**Comment by roamye** [comment]
@kamerynB 

This ticket is currently being blocked by https://github.com/project-lux/lux-marklogic/issues/65. I am unsure if this would prevent the HAL link from being created for this issue. If it does not, would you be able to tackle creating this HAL link so it can unblock https://github.com/project-lux/lux-frontend/issues/8?

**Comment by kamerynB** [comment]
@roamye It is blocking it because we don't have a search term for objects influenced by a person. Marklogic needs to define the relationship with the search term. The search terms then allow the HAL links to be created.

**Comment by clarkepeterf** [comment]
I unblocked this in ML and I will complete this sprint

**Comment by clarkepeterf** [comment]
@jffcamp @azaroth42 based on our conversation I'm moving forward with the following:

The data will be merged with exisiting HAL links to create tabs called:

"Objects Created or Encountered or Influenced By" and "Works Created, Published, or Influenced By"

**Comment by roamye** [comment]
@clarkepeterf & @kamerynB - the UAT link shows the first tab 'Objects created or encountered or influenced by' but does not show the 'works created, published or influenced by' tab. I have tried to find a UAT link for this but can't find one. Can one of you identify a UAT link for the second tab?

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD as JSON file shows updated HAL links...
 
lux:agentCreatedPublishedWork" -> lux:agentCreatedPublishedInfluencedWork
lux:agentMadeDiscoveredItem" -> "lux:agentMadeDiscoveredInfluencedItem"

Closing.
