### ISSUE TITLE
Add HAL link for Objects and Works that are subjects of a work

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-middletier#28]
**Problem Description:**
There is no HAL link for rendering data for objects/works that are subjects of another work.

**Expected Behavior/Solution:**
Add a HAL link onto Objects and Works that are the subject of another work.

**Requirements:**

- [x] ML query - @clarkepeterf 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Peter
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux.collections.yale.edu/data/text/5ad5d97a-1b16-42c4-ad5e-145b2371643b 
- https://lux-front-tst.collections.yale.edu/view/text/2bc1c5a0-0085-449f-bf60-ca685d72f128

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-frontend/issues/62
- Blocked by: https://github.com/project-lux/lux-marklogic/issues/66

**Related Github Issues:**

- ~https://github.com/project-lux/lux-middletier/issues/31 (dupe)~

**Related links:**

- https://www.bugherd.com/projects/284041/tasks/1792

**Wireframe/Mockup:**
N/A

**Comment by kamerynB** [comment]
@clarkepeterf Does this issue require a ML issue? I'm not sure if this relationship exists currently.

**Comment by clarkepeterf** [comment]
@kamerynB The UAT for this ticket is incorrect. Both of those are works that have other works about them. We want to search in the opposite direction (items that are the subject of the current work, or works that are the subject of the current work)

Work about an object:
https://lux-front-tst.collections.yale.edu/data/text/4a0a53e4-c8d5-4fff-8c00-bf3d1e10b4fc

Work about another work:
https://lux-front-tst.collections.yale.edu/data/text/29b98ec5-b8c9-405e-a83f-03e2eb5a427b

**Comment by clarkepeterf** [comment]
@kamerynB Ah, I'm looking at the frontend requirements, what you want is to use the work `aboutItem` and work `aboutWork` search terms on object and work pages. The search term is about, but then that lets you display "Subject Of" on the entity page

**Comment by kamerynB** [comment]
@clarkepeterf I believe I've gotten things straight now.

**Comment by roamye** [comment]
Approved by UAT 9/12

**Comment by roamye** [comment]
Looks good in PROD. Closing.
