### ISSUE TITLE
Add HAL link for related People and Groups on Event pages - supports FE 8

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-middletier#29]
**Problem Description:**
There is no HAL link for retrieving related people and groups on events to support https://github.com/project-lux/lux-frontend/issues/8

**Expected Behavior/Solution:**
Add the HAL link for getting related people and groups to events.

**Requirements:**

- [x] [ML query - @clarkepeterf ](https://github.com/project-lux/lux-marklogic/issues/67)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - TBD
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/data/activity/6e09857c-6b08-4155-a3b9-c7055d688d92

**Dependencies/Blocks:**

- Blocked by: https://github.com/project-lux/lux-marklogic/issues/67
- Blocking: https://github.com/project-lux/lux-frontend/issues/8

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/8

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
looks good in prod, closing.
