### ISSUE TITLE
HAL Link for "Subject of" to Work and Object Pages

### ISSUE THREAD

**Issue by ar2674** [project-lux/lux-middletier#31]
**Problem Description:**
The front end wishes to add  "Subject Of" to the About section and display relevant links within it for all Works and Object pages where applicable. 
This will allow Works and Object pages to be linked back to a subject of another work. 

**Expected Behavior/Solution:**
Create a HAL Link which returns the following query: 
TBD - Dependent on when Peter creates the HAL link. 

**Requirements:**
Once HAL link is created, "Subject Of" will appear under Work and Object Pages and contain relevant links. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] ~Backend requirements - TBD~
- [ ] ~Frontend requirements- TBD~
- [ ] ~Questions~
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/text/2bc1c5a0-0085-449f-bf60-ca685d72f128 

**Dependencies/Blocks:**
- Dependency: https://github.com/project-lux/lux-frontend/issues/62

**Related Github Issues:**

**Related links:**

~**Wireframe/Mockup:**~
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by ar2674** [comment]
@clarkepeterf I have created this as a HAL ticket for [front-end62](https://github.com/project-lux/lux-frontend/issues/62). If I missed anything please feel free to update.

**Comment by kamerynB** [comment]
@ar2674 Please close as this is a dupe of the issue I created #28.

**Comment by ar2674** [comment]
Thanks @kamerynB, closing as this is a dupe. and I have added #28 onto https://github.com/project-lux/lux-frontend/issues/62.

**Comment by ar2674** [comment]
closing
