### ISSUE TITLE
Remove duplicates in estimate requests for HAL links (from 50)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#4]
### Problem Description
Middle tier uses the backend's searchWillMatch endpoint to decide whether to include a HAL link in the document. If the estimated number of results is 0, the HAL link that corresponds to the search will be omitted. 

The searchWillMatch query is a combined query that contains multiple queries, and currently often contains duplicates which will affect the performance. 

It won't be a simple task because of the way the queries are shared (between estimations and real searches), combined, and separated.

### Requirements
Remove the duplicates.

**Comment by roamye** [comment]
Old ticket ( https://git.yale.edu/lux-its/lux-backend/issues/50 ) does not show any further comments/information than what is in this ticket.

**Comment by roamye** [comment]
@gigamorph - 

What is needed for this to be promoted to prioritization review? (besides formatting the issue)

**Comment by roamye** [comment]
tix forming mtg 6/17
will require significant refactoring and UAT is in the middle-tier. Ticket is still valid.

**Comment by gigamorph** [comment]
Done - https://github.com/project-lux/lux-middletier/pull/100/files
