### ISSUE TITLE
HAL Link for Sets on Event Pages

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-middletier#40]
**Problem Description:**
the front end wishes to add missing data to set/collection pages by creating a HAL link that will add information of a  Set to the Event. 

**Expected Behavior/Solution:**
Create a HAL link which returns the following query: 

`{"_scope": "event", used":{"id":"${SET_ID}"}}`
Hal LINK query name: lux:setEvents

**Requirements:**
Once HAL link is created, Set information will appear under Event. (Please see mock of dependency issue) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] ~Frontend requirements- TBD~
- [ ] ~Questions~

**UAT/LUX Examples:**
https://lux-front-tst.collections.yale.edu/view/set/664c4aeb-532f-46a2-9db8-4d0b51c73a64 should render information related to https://lux-front-tst.collections.yale.edu/view/activity/ef9bfa8b-1d19-4b44-a004-a5ab75cdf6d7

**Dependencies/Blocks:**
Dependency:  https://github.com/project-lux/lux-frontend/issues/88

**Related Github Issues:**
- https://github.com/project-lux/lux-middletier/issues/30 (dupe, will need to close when it re-appears) 
**Related links:**

~**Wireframe/Mockup:**~
~Place wireframe/mockup for the proposed solution at end of ticket.~

**Comment by roamye** [comment]
Re-created this issue as it was originally: https://github.com/project-lux/lux-middletier/issues/30 but it is hidden as ar2674 created that issue.

**Comment by roamye** [comment]
@clarkepeterf We need to know the name for the query HAL Link in order for this tix to move forward. Thank you.

**Comment by roamye** [comment]
@clarkepeterf in order for this ticket to move forward we need the name for the query HAL link. Please let me know what it is so I can update the tix. Thank you.

**Comment by clarkepeterf** [comment]
@roamye the HAL link name you created works for me

**Comment by clarkepeterf** [comment]
@clarkepeterf test this query with the example links

**Comment by clarkepeterf** [comment]
@kamerynB  the bug is fixed, this query works now

**Comment by kamerynB** [comment]
@clarkepeterf Thank you Peter. I'll test it out

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Added to the release notes of 7/16 - but will close once FE 88 is approved/deployed in the next cycle.

**Comment by roamye** [comment]
FE88 looks good in prod. Closing.
