### ISSUE TITLE
Add HAL link for research dataset

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-middletier#44]
**Problem Description:**
A HAL link is missing for connection between datasets and projects.

**Expected Behavior/Solution:**
The HAL link should be added.

**Requirements:**

- [x] Add: https://lux-front-rdata.collections.yale.edu/api/search/work?q=%7B%22causedByProject%22%3A%7B%22id%22%3A%22https://lux.collections.yale.edu/data/activity/52724784-8b08-44a9-868a-a7880238f7b5%22%7D%7D&page=1&pageLength=20

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Kam
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-rdata.collections.yale.edu/data/activity/80a17e21-bb72-46d9-844b-183946a1ebf5
- https://lux-front-rdata.collections.yale.edu/view/activity/6b27737e-90f7-4ca6-9175-ac2e0159a7f5

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-frontend/issues/146

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by azaroth42** [comment]
Here's a link to the now-functioning search interface:

https://lux-front-rdata.collections.yale.edu/view/results/works?q=%7B%22causedByProject%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F48df4673-ebcf-4a19-8813-f9fad520113b%22%7D%7D

**Comment by prowns** [comment]
@azaroth42 - can this be closed, or is there more work to do on this?

**Comment by prowns** [comment]
Leave open for additional work.

**Comment by kamerynB** [comment]
Per Rob: Closing.

cc: @prowns @roamye
