### ISSUE TITLE
Add HAL link for Related Locations Accordion Events page - Supports FE 9

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-middletier#45]
**Problem Description:**
Need to create a HAL link that will return a related list for an Event's related Places

**Expected Behavior/Solution:**
Create `lux:eventRelatedPlaces` HAL link

**Requirements:**

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**
`lux:eventRelatedPlaces` HAL link will exist in the data for this entity:
https://lux-front-tst.collections.yale.edu/data/activity/25018568-d5d8-4a1c-b785-7e50b8e5e453

**Dependencies/Blocks:**

- Blocking: https://github.com/project-lux/lux-frontend/issues/9
- Blocked by: https://github.com/project-lux/lux-marklogic/issues/95

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by clarkepeterf** [comment]
Need place: relatedToEvent added to related lists in Marklogic

**Comment by roamye** [comment]
Looks good in prod, closing.
