### ISSUE TITLE
Remove HAL link conceptDepictedAgentFromRelatedWorks 

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-middletier#46]
**Problem Description:**
This HAL link is not needed as it is renders similar data to `conceptRelatedAgents`.

**Expected Behavior/Solution:**
The HAL link config will be removed and will no longer be visible in the data.

**Requirements:**

- [x] Remove the config

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Kam
- [x] Frontend requirements - Kam, frontend config will be removed
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/data/concept/bb258a2e-5050-4bef-93f6-ac24276f1878
- https://lux.collections.yale.edu/data/concept/bb258a2e-5050-4bef-93f6-ac24276f1878 (prod)

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/155

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2094

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
@kamerynB Hi Kam, was this deployed? If so I will move it to "Awaiting Review"

**Comment by kamerynB** [comment]
@roamye Yes I will move to Awaiting Review.

**Comment by roamye** [comment]
Approved by UAT
