### ISSUE TITLE
Update Hal Links for Archive/Set Sorting - supports FE 27

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#47]
**Problem Description:**
Archives/Sets will have a new sort option, which we will want to apply to HAL links that display their members (lux:setIncludedItems and lux:setIncludedWorks)

**Expected Behavior/Solution:**
Archives/Sets members are sorted in their HAL links  (lux:setIncludedItems and lux:setIncludedWorks)

**Requirements:**
- ML Update - (TBD @brent-hartwig)

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
- [x] Backend requirements - (https://github.com/project-lux/lux-marklogic/issues/90) @brent-hartwig 
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- If you look at an Archive record and its HAL link values ("href") for `lux:setIncludedItems` and `lux:setIncludedWorks`, they now include `&sort=itemArchiveSortId:asc` and `&sort=workArchiveSortId:asc`, respectively. [Example here](https://lux-front-tst.collections.yale.edu/data/set/64c33170-030b-4482-8baf-559a02854bfe)
- [PRD counterexample](https://lux.collections.yale.edu/data/set/64c33170-030b-4482-8baf-559a02854bfe) (those links don't have `&sort=...`)

**Dependencies/Blocks:**

- Blocked By: ~ML Issue TBD @brent-hartwig~ https://github.com/project-lux/lux-marklogic/issues/90
- Blocking: https://github.com/project-lux/lux-frontend/issues/27

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- https://github.com/project-lux/lux-marklogic/issues/38 
It has been determined that this specific issue is not directly related to 38 (semantic sort)

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
@clarkepeterf @brent-hartwig 
Do we have a ML issue created which is blocking this issue? or is it still TBD? 

cc: @prowns

**Comment by brent-hartwig** [comment]
@roamye, please see https://github.com/project-lux/lux-marklogic/issues/90

**Comment by roamye** [comment]
Looks good in prod, closing.
