### ISSUE TITLE
Automate HAL link testing (from 67)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#5]
### Problem Description

```
From @bh635:

The initial goal is to detect conflicts between a) search criteria associated with HAL links and b) 
the backend's search term configuration.  

It is believed the middle tier:

1. Exclusively consumes the `searchWillMatch` when constructing the HAL links.
2. Generates all HAL links when an entity page is requested (and a profile is not specified).

If true, an automated test could submit one entity page request per entity then check the 
`hasOneOrMoreResult` response body properties.  When the value is `-1`, the search criteria 
should be checked.
```

### Discussion
- Implementation - https://git.yale.edu/lux-its/lux-backend/issues/67#issuecomment-24771

Old ticket: https://git.yale.edu/lux-its/lux-backend/issues/67

**Comment by jffcamp** [comment]
QA does have the ability to test APIs and not go through the UI

**Comment by roamye** [comment]
I believe this should be propose close. Isn't this what the HAL link test cases in QA accomplished? or is there something else needed for this? 

@gigamorph, @jffcamp
