### ISSUE TITLE
Update HAL link for Related Subjects on event pages and make label change. 

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-middletier#51]
**Problem Description:**
The Related Subjects HAL link currently does not return the correct relationship.

**Expected Behavior/Solution:**
The HAL link should be changed to return a related list query.

**Requirements:**

- [ ] Change the current HAL link to the following: TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Peter, ML ticket
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**
- There is now a `lux:eventRelatedConcepts` HAL link in event data: https://lux-front-tst.collections.yale.edu/data/activity/8f7424b8-2b14-4f6d-8ba5-fc210b55587b
- PRD counterexample (doesn't have that link): https://lux.collections.yale.edu/data/activity/8f7424b8-2b14-4f6d-8ba5-fc210b55587b

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-marklogic/issues/96
- Blocking: https://github.com/project-lux/lux-frontend/issues/180

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
json has the lux:eventRelatedConcepts in prod. good to close.
