### ISSUE TITLE
Remove Hierarchy Endpoints (from 72)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#6]
Remove Hiearchy Endpoints from the middle tier after the frontend is able to handle them on its own (do this ticket after https://git.yale.edu/lux-its/lux-web/issues/1590) 
Note: 1590 is closed. 

Blocked by: 
- https://github.com/project-lux/lux-frontend/issues/25

Blocking: 
- https://github.com/project-lux/lux-frontend/issues/84

Bugherd: https://www.bugherd.com/projects/284041/tasks/1582

**Comment by prowns** [comment]
@kamerynB - was this deployed?
