### ISSUE TITLE
Update HAL Links for Updated memberOf / containing fields

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#60]
**Problem Description:**
Some fields related to `memberOf` and `containing` were updated in Marklogic (https://github.com/project-lux/lux-marklogic/issues/135)
**Expected Behavior/Solution:**
Update HAL links to be compatible with new field configuration in ML (https://github.com/project-lux/lux-marklogic/issues/135)

**Requirements:**

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- [this object](https://lux-front-tst.collections.yale.edu/data/object/29511e38-d50e-4b07-a5a8-1eeb62f3d18f) has a `lux:itemEvents` and `lux:itemDepartment` HAL link which both contain the string "containingItem"
- [this set](https://lux-front-tst.collections.yale.edu/data/set/7ef37f20-1677-4081-959f-b2a00d1d5396) has a `lux:setDepartment` HAL link which contains the string "containingSet". It also has a `lux:setItemsWithImages" HAL link
-
Fixes https://github.com/project-lux/lux-middletier/issues/14
and https://github.com/project-lux/lux-frontend/issues/28

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-marklogic/issues/135

**Related Github Issues:**

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

**Related links:**

~~- These links can consist of resources, bugherds, etc.~~

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
json record looks good in prod, closing.
