### ISSUE TITLE
Create middle tier/frontend for LUX new data

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#63]
**Problem Description:**
Create middle tier and frontend for testing new datasets

**Dependencies**
- Depends on https://github.com/project-lux/lux-marklogic/issues/164

**Comment by gigamorph** [comment]
Provisioned all components.
Load balancer: https://dev-lux-data-alb-429292828.us-east-1.elb.amazonaws.com/

**Comment by roamye** [comment]
I think this should be closed since the data dev environment is working...?

**Comment by prowns** [comment]
UAT - close
