### ISSUE TITLE
Pagination of facets

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#65]
**Problem Description:**
Facets will be paginated to reduce network load.  

**Expected Behavior/Solution:**
Support pagination as implemented with https://github.com/project-lux/lux-marklogic/issues/160 and https://github.com/project-lux/lux-marklogic/issues/161
https://github.com/project-lux/lux-frontend/issues/252 

**Dependencies/Blocks:**
- Blocked by
  - https://github.com/project-lux/lux-marklogic/issues/160 
  - https://github.com/project-lux/lux-marklogic/issues/161

**Comment by prowns** [comment]
@gigamorph - this is moved to dev board for 6/7 performance test.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing looks good in prod.
