### ISSUE TITLE
Determine means to temporarily bypass the web cache

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/lux-middletier#75]
**Problem Description:**
During [18 Jun 24's performance test](https://github.com/project-lux/lux-marklogic/issues/181), there were approximately 56K more requests of CloudFront than the middle tier.  A load balancer and web cache instances are between the two and even though it was disabled, not all capabilities appear to be disabled.  The scope of this ticket is to research how we could temporarily completely bypass the web cache during performance tests; i.e., configure CloudFront to the middle tier load balancer.

**Expected Behavior/Solution:**
Determine how to route requests through the web cache or not through it in a manner that only takes minutes for the switch to occur.

**Requirements:**
See above

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~- [ ] Wireframe/Mockup - Mike~
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [x] Backend requirements - None
- [x] Frontend requirements - None
- [ ] Are new regression tests required for QA - Amy
- [x] Compels performance test?  No.  Just a research ticket.  Once implemented it still would not justify its own performance test.  Not one of its own.  Just check web cache request counts during/after a future performance test.
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
None.  _If_ this ticket also becomes the implementation, one with AWS Console access could verify by checking request counts at various levels in the stack.  This could and should be done in advance of a performance test.

**Dependencies/Blocks:**
This issue neither blocks nor is blocked by another.

**Related Github Issues:**
[18 Jun 24's performance test](https://github.com/project-lux/lux-marklogic/issues/181)

**Related links:**
None

**Wireframe/Mockup:**
N/A

**Comment by brent-hartwig** [comment]
Based on a team conversation today, the decision on whether to implement this ticket is blocked on upcoming discussions on how to perform a performance test.  cc: @jffcamp, @prowns

**Comment by roamye** [comment]
skipped prioritization review - needs to be reviewed at tomorrows meeting.

**Comment by brent-hartwig** [comment]
I propose we close this ticket.  It falls within the 'false economy' argument and our plans to come up with a performance test that executes while the middle tier cache is enabled.

**Comment by roamye** [comment]
@brent-hartwig - thanks Brent. Last weeks UAT had a lot of issues. I have added this and other issues, which were not discussed, to next weeks UAT.

**Comment by brent-hartwig** [comment]
During the last performance test discussion, there was consensus that the new (yet-to-be-implemented) approach would leave this cache enabled.  I do not believe this needs to be pursued for the current performance test.  #stillProposeClose

**Comment by roamye** [comment]
Approved by UAT 9/12 to close
