### ISSUE TITLE
Expanding Search Query for Objects in Collection

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-middletier#76]
**Problem Description:**
Under the group record `Yale University Art Gallery, 1940 -` the `Objects in Collection` Tab only shows three results. However, there should be more results listed as there are multiple objects under Yale University Art Gallery. ([example](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors&ip=1&if=%7B%22AND%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2Fcb466280-c7f2-4edd-8ec2-bf84c64b9150%22%7D%7D%5D%7D&facetRequest=true)) 

Note: The results under YUAG is caused by how their data is vended. All other Units do not show as a collection because collections are handled by the individual departments. 
- [Yale University Art Gallery](https://lux.collections.yale.edu/view/group/6086b58d-941d-41e3-87c1-e00e96952ffb)
- [Yale University Library](https://lux.collections.yale.edu/view/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9)
- [YPM ](https://lux.collections.yale.edu/view/group/0a5ed086-396b-4cc2-8120-fdc3f8953ce2)
- [YCBA](https://lux.collections.yale.edu/view/group/0e8bc04a-6538-4792-b82a-9e0751857e7d)

**Expected Behavior/Solution:**
Move forward with expanding the search query to include an additional `member of` block that can search for all objects in a specific collection. This query will be updated for the 'Objects in Collection' tab 

**Requirements:**
- Tabs "Objects in Collection" will be re-queried to contain the extra `member of` block needed to find all objects in a collection. 
- AS Query will contain an extra `member of` block. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

Units' Group pages will have an "Objects in Collection" tab with a "Show all X Results" link to a query like [this.](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F6086b58d-941d-41e3-87c1-e00e96952ffb%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F6086b58d-941d-41e3-87c1-e00e96952ffb%22%7D%7D%7D%7D%5D%7D)

Group pages
- [YUAG](https://lux.collections.yale.edu/view/group/6086b58d-941d-41e3-87c1-e00e96952ffb)| [TST](https://lux-front-tst.collections.yale.edu/view/group/41310ca5-8137-45fe-ac2c-a6a04e2235f1)
- [Yale University Library](https://lux.collections.yale.edu/view/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9) | [TST](https://lux-front-tst.collections.yale.edu/view/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9)
- [YPM ](https://lux.collections.yale.edu/view/group/0a5ed086-396b-4cc2-8120-fdc3f8953ce2) | [TST](https://lux-front-tst.collections.yale.edu/view/group/0a5ed086-396b-4cc2-8120-fdc3f8953ce2)
- [YCBA](https://lux.collections.yale.edu/view/group/0e8bc04a-6538-4792-b82a-9e0751857e7d) | [TST](https://lux-front-tst.collections.yale.edu/view/group/0e8bc04a-6538-4792-b82a-9e0751857e7d)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
-  [YUL data fix to remove Yale University Library as collection name](https://git.yale.edu/LUX/unit-data/issues/129)
- Old Issue: https://github.com/project-lux/lux-frontend/issues/221

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2176
- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/163148482/2d07e372-821d-4ad9-b956-0818e687de03)

**Comment by roamye** [comment]
From old ticket: 
https://github.com/project-lux/lux-frontend/issues/221#issuecomment-2192425919

**Comment by prowns** [comment]
@clarkepeterf - this is just for units.

**Comment by clarkepeterf** [comment]
Ok. I am updating the UAT which mentions Sets, but that does not apply. Thanks @prowns

**Comment by roamye** [comment]
Approved by UAT 7/22

**Comment by roamye** [comment]
Closing in PROD.
