### ISSUE TITLE
Update setItemsWithImages HAL Link

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#77]
**Problem Description:**
The setItemsWIthImages HAL link takes a long time to run sometimes, especially on Collections with a large number of items. This causes the Collection Entity pages and Collection lines on Object results to load slowly

**Expected Behavior/Solution:**
Update the setItemsWIthImages HAL link to check if the Set is an Archive ("identifier":"http://vocab.getty.edu/aat/300375748") as this is the only place the query will have results. The check for the Archive classification helps short-circuit the search for Collections so that the search will be faster.

**Requirements:**

- Update the setItemsWIthImages HAL link to check if the Set is an Archive ("identifier":"http://vocab.getty.edu/aat/300375748") 
- Have this deployed to the lower environments, including TST, prior to the 7/17 performance test

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- [Offsite Storage, Yale University Library](https://lux-front-dev.collections.yale.edu/data/set/4b2b3586-7eaf-4b47-9af5-476e41a5f38c) 
- [Paintings and Sculpture Collection, Yale Center for British Art](https://lux-front-dev.collections.yale.edu/view/set/1f8f20d5-a5e1-4422-8624-42debfe14eba)
should not take a long time to load

~~**Dependencies/Blocks:**~~

**Related Github Issues:**
- https://github.com/project-lux/lux-middletier/issues/14

~~**Related links:**~~

~~**Wireframe/Mockup:**~~

**Comment by roamye** [comment]
@clarkepeterf - what are we supposed to be seeing in the first UAT link? I tried looking for the setItemsWithImages in prod/dev/tst but don't see it within the JSON code. Is that what I am supposed to be seeing? 

Also is there another UAT link for the collection in search results? I would like to use: https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22painting%22%2C%22_lang%22%3A%22en%22%7D&sq=painting but unsure if there is another search which has more object results where the collections line was taking long to load.

**Comment by prowns** [comment]
I believe this is https://lux-front-tst.collections.yale.edu/view/set/4b2b3586-7eaf-4b47-9af5-476e41a5f38c, which was causing timeouts in performance test, per [this teams chat](https://teams.microsoft.com/l/message/19:351e0281aaa144d0812b960d216958c6@thread.tacv2/1720746400678?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1720704235447&teamName=ML%2F%20Cultural%20Heritage%20Support&channelName=1%20-%20LUX_ML&createdTime=1720746400678).

**Comment by roamye** [comment]
Approved by UAT 7/22

**Comment by roamye** [comment]
Looks good in PROD. Closing.
