### ISSUE TITLE
Move Ports for Advanced Search Config and Data Constants

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#78]
**Problem Description:**
The Queue for the group-1 (FKA "fast lane")  port (mlProxy) fills up during performance tests, leading to a bunch of 504s. We want to handle the Advanced Search Config and Data Constants requests on the other, group-2, port (mlProxy2) (FKA "slow lane")

**Expected Behavior/Solution:**
Advanced Search Config and Data Constants are handled with mlProxy2

**Requirements:**
Do not adjust threads, just move Advanced Search Config and Data Constants to mlProxy2
Deploy to lower environments prior to 7/17 performance test.

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- @clarkepeterf will share ML logs with these requests on their new ports

~~**Dependencies/Blocks:**~~

~~**Related Github Issues:**~~

~~**Related links:**~~

~~**Wireframe/Mockup:**~~

**Comment by brent-hartwig** [comment]
Using 18 Jun 24's performance test (https://github.com/project-lux/lux-marklogic/issues/181) as an example, this ticket's changes would have increased the percent of requests to lux-request-group-2 from 1.15% to 18.43%.

Breakdown without this ticket's changes:

| Endpoint                      | lux-request-group-1 | lux-request-group-2 | Total     | Total % |
|-------------------------------|---------------------|---------------------|-----------|---------|
| Search                        |                     |  2,306              |  2,306    | 0.85%   |
| Related Lists                 |                     |  828                |  828      | 0.30%   |
| Facets                        |  27,360             |                     |  27,360   | 10.07%  |
| Search Will Match             |  26,876             |                     |  26,876   | 9.90%   |
| Search Estimate               |  14,470             |                     |  14,470   | 5.33%   |
| Document                      |  146,483            |                     |  146,483  | 53.94%  |
| Advanced search configuration |  23,189             |                     |  23,189   | 8.54%   |
| Auto complete                 |  -                  |                     |  -        | 0.00%   |
| Data constants                |  23,737             |                     |  23,737   | 8.74%   |
| Person roles                  |  -                  |                     |  -        | 0.00%   |
| Search info                   |  -                  |                     |  -        | 0.00%   |
| Stats                         |  3,654              |                     |  3,654    | 1.35%   |
| Translate                     |  2,681              |                     |  2,681    | 0.99%   |
| **Request count totals**          |  **268,450**            |  **3,134**              |  **271,584**  | **100.00%** |
| **Percent of requests**           | **98.85%**              | **1.15%**               | **100.00%**   | |

Breakdown with this ticket's changes:

| Endpoint                      | lux-request-group-1 | lux-request-group-2 | Total     | Total % |
|-------------------------------|---------------------|---------------------|-----------|---------|
| Search                        |                     |  2,306              |  2,306    | 0.85%   |
| Related Lists                 |                     |  828                |  828      | 0.30%   |
| Facets                        |  27,360             |                     |  27,360   | 10.07%  |
| Search Will Match             |  26,876             |                     |  26,876   | 9.90%   |
| Search Estimate               |  14,470             |                     |  14,470   | 5.33%   |
| Document                      |  146,483            |                     |  146,483  | 53.94%  |
| Advanced search configuration |  -                  |  23,189             |  23,189   | 8.54%   |
| Auto complete                 |  -                  |                     |  -        | 0.00%   |
| Data constants                |  -                  |  23,737             |  23,737   | 8.74%   |
| Person roles                  |  -                  |                     |  -        | 0.00%   |
| Search info                   |  -                  |                     |  -        | 0.00%   |
| Stats                         |  3,654              |                     |  3,654    | 1.35%   |
| Translate                     |  2,681              |                     |  2,681    | 0.99%   |
| **Request count totals**                        |  **221,524**            |  **50,060**             |  **271,584**  | **100.00%** |
| **Percent of requests**           | **81.57%**              | **18.43%**              | **100.00%**   | |

I would find it interesting to capture the following metrics after this ticket partakes in a performance test:

- [ ] Number of 504s from the ML load balancer
- [ ] Number of failed retries by the data service proxies
- [ ] The typical metrics we capture for the app server request queues (in [Perf: Key Metrics](https://docs.google.com/spreadsheets/d/1uu6aL7yn047yyiZ4auujpTXnlwm01sgWZQ50ht-X4M4/edit?gid=774672157#gid=774672157))

And of course what got us to do this now: was the system able to provide the data constants and advanced search form configuration more often during a performance test than during [11 Jul 24's performance test](https://teams.microsoft.com/l/message/19:b443751df2d54a078c585caef5a9a57c@thread.tacv2/1720718350710?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=380f1dda-57b8-4f5f-a737-95851192656e&parentMessageId=1720718350710&teamName=LUX%20Gating%20and%20QA&channelName=QA%20Testing&createdTime=1720718350710) (private)?

**Comment by brent-hartwig** [comment]
@jffcamp and @clarkepeterf, do we plan to deploy this to TST in advance of tomorrow's performance test (https://github.com/project-lux/lux-marklogic/issues/226)?

**Comment by roamye** [comment]
@clarkepeterf - I am assuming this is unreviewable, Will the ML logs with the requests on their new ports be available on Monday? Or is that something only @jffcamp reviews with @brent-hartwig ?

**Comment by brent-hartwig** [comment]
@roamye, I can confirm that this change was present in TST during the 17 Jul performance test (https://github.com/project-lux/lux-marklogic/issues/226); however, @clarkepeterf, the changes do not appear to have reached a release branch or tag yet.

**Comment by roamye** [comment]
Approved by UAT 7/22

**Comment by roamye** [comment]
This has been DPLYD to PROD and is unreviewable. Closing.
