### ISSUE TITLE
Update itemEvents HAL Link To Sort Events (from 105)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#8]
### Expected Behavior

The lux:itemEvents hal link will return events sorted by date in ascending order (oldest top, newest bottom)

### UAT/Testing
In the HAL link, there will be a sort parameter.  UAT can happen via 1266 (below)

### Prerequisite for

[Sort item events by year (from 1266) #18](https://github.com/project-lux/lux-frontend/issues/18)

**Comment by clarkepeterf** [comment]
Deployed to DEV, changes should show up in the existing HAL link on the frontend, no frontend changes required
