### ISSUE TITLE
Update This Project To Use ES6+ import/export rather than CommonJS require/module.exports 

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#86]
**Problem Description:**
This codebase currently uses CommonJS require / module.exports to share code across files. It is possible to switch to ES6 import/export which is a more compact format and allows for importing only the parts of a file which are needed.

**Expected Behavior/Solution:**
Convert to using ES6 imports and exports

**Requirements:**

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

Does not impact functionality of the application. Only affects developer experience.

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

**Related links:**

~~- These links can consist of resources, bugherds, etc.~~

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by clarkepeterf** [comment]
@roamye I forgot this ticket existed, but I ended up making this change in this PR:
https://github.com/project-lux/lux-middletier/pull/107/commits

So, the middle tier has this change already

**Comment by roamye** [comment]
approval to close UAT
