### ISSUE TITLE
Create WorksAboutEvent HalLink (from 107)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#9]
### Problem Description 
- The frontend wishes to display Works about Concepts influenced by Events on Event pages

### Expected Behavior
- Create a HAL link which returns the following query:

```
{
    "aboutConcept": {
        "influencedByEvent": {
            "id": "${EVENT_ID}"
        }
    }
}
```

### Dependency For
 [Add Works About tab and list to events (from 1303) #19](https://github.com/project-lux/lux-frontend/issues/19)

**Comment by clarkepeterf** [comment]
@kamerynB the HAL Link name for this is 'lux:eventWorksAbout'

**Comment by prowns** [comment]
deployed
