### ISSUE TITLE
Link to object from unit provided identifier (from 829)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-middletier#93]
**Problem Description:**
There is a request to be able to link directly to an object page in LUX based on a unit-provided identifier. In this way, a unit will be able to construct a link to the item without knowing the LUX URI. (request from YUAG)

Example: 
Rather than using this link: https://lux-front-prd.collections.yale.edu/view/object/72c1ebe6-d0b4-4ac1-8632-19d854b2bcd9
A unit could call an API, pass unit code (YUAG) and Record Identifier/cmsid (126776), or whatever else would make it a unique call, and return that specific object page.

**Expected Behavior/Solution:**
 
~~- [ ] Create an index of only accession numbers (will be needed for YPM and other subsequent uses anyway)~~
  - Existing identifier index
~~- [ ] Expose new field to advanced search (say identifier-accession)~~
  - existing identifier field
- [ ] Extend above query to use new field and AND with the unit to avoid identifier collisions
  ~~- Need clarification from @azaroth42 ~~
  - will follow up if needed
- [ ] Create a little API that takes the accession number and code for the unit, calls the query, and redirects the caller to the object web page.  _e.g. lux.collections.yale.edu/api/object-redirect?identifier=1941.380&unit=yuag
gives a 302 redirect to https://lux.collections.yale.edu/view/object/2dbabf81-dd18-4794-9998-a883c1f6ae91_
- [ ] Then the units can embed: <a href="https://lux.collections.yale.edu/api/object-redirect?identifier=1941.380&unit=yuag">This object in LUX</a> without knowing the UUID for it, and have the browser just do the right thing

**Requirements:**

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Heather~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] Backend requirements - TBD
- [ ] ~Frontend requirements- TBD~
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**Dependencies/Blocks:**

**Related Github Issues:**

**UAT/LUX Examples:**
Some example mappings:
 - https://lux-front-tst.collections.yale.edu/api/resolve/objects/lml/4190 -> https://lux-front-tst.collections.yale.edu/view/object/1685dd86-52ce-43f6-aa35-5c063ba2fc02
 - https://lux-front-tst.collections.yale.edu/api/resolve/objects/ycba/4190 -> https://lux-front-tst.collections.yale.edu/view/object/3ef6b21f-5aea-4b4c-96b7-234fa9bdab98
 - https://lux-front-tst.collections.yale.edu/api/resolve/objects/yuag/4190 -> https://lux-front-tst.collections.yale.edu/view/object/fa392bc3-b0b9-4a75-b39e-dfb8937ed082
 - https://lux-front-tst.collections.yale.edu/api/resolve/objects/yuag/ypm:ecatalogue:irn:1177237 -> https://lux-front-tst.collections.yale.edu/view/object/ca8b8be4-d273-404b-8874-df1fb1264b83
 - https://lux-front-tst.collections.yale.edu/api/resolve/objects/pmc/B03161 -> https://lux-front-tst.collections.yale.edu/view/object/d0232d28-2f63-4134-8929-09c4e42703df
 -  https://lux-front-tst.collections.yale.edu/api/resolve/objects/yul/ils:yul:mfhd:10015204 -> https://lux-front-tst.collections.yale.edu/view/object/17a849ab-d0b0-4f0f-a0b4-7100e8263594
 - https://lux-front-tst.collections.yale.edu/api/resolve/works/yul/ils:yul:17006717 -> https://lux-front-tst.collections.yale.edu/view/text/2bdc4e15-3159-4641-b7a6-6258fced91ad

**Comment by clarkepeterf** [comment]
@azaroth42 For the purpose of this ticket - How should I link Works to a Unit?

Is it true that a Work for a unit would be carried by an Object that unit is responsible for?

**Comment by azaroth42** [comment]
Urgh, good question.

No ... because of our nemesis:  https://lux.collections.yale.edu/view/object/4a3d1b7d-9657-46dc-8363-18866dc4a6ed 

For now, 99.99% of use cases would be solved by assuming all work requests like this are from/for YUL records.

@prowns #agenda for the 0.001% :(

**Comment by clarkepeterf** [comment]
@azaroth42

Even if it maps to two different units, I think the query would still work. As long as there is not another work with the same identifier.

Here are example queries for our nemesis:

[YCBA query](https://lux-front-dev.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22identifier%22%3A%22https%3A%2F%2Fycba-lux.s3.amazonaws.com%2Fv3%2Fvisual%2F82%2F8288d752-63d8-4a6d-90b3-9e8668da505a.json%22%7D%2C%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500303557%22%7D%7D%7D%7D%7D%5D%7D)
[YUAG query](https://lux-front-dev.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22identifier%22%3A%22https%3A%2F%2Fmedia.art.yale.edu%2Fcontent%2Flux%2Fvis%2F307686.json%22%7D%2C%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500303559%22%7D%7D%7D%7D%7D%5D%7D)

If that works, let me know!


P.s. the [work of our nemesis](https://lux.collections.yale.edu/view/visual/a121e511-e010-40c0-80c7-bad50eff2844) doesn't have any assigned identifiers. Just equivalent ids. So those are what I used in the queries above.
Equivalent IDs below:

```
  "equivalent": [
      {
          "id": "https://ycba-lux.s3.amazonaws.com/v3/visual/82/8288d752-63d8-4a6d-90b3-9e8668da505a.json",
          "type": "VisualItem",
          "_label": "\"Portrait of Lynette Yiadom-Boakye, Jacob Morland of Capplethwaite\" - Visual Content"
      },
      {
          "id": "https://media.art.yale.edu/content/lux/vis/307686.json",
          "type": "VisualItem",
          "_label": "Portrait of Lynette Yiadom-Boakye, Jacob Morland of Capplethwaite [Visual Content]"
      }
  ]
```

**Comment by clarkepeterf** [comment]
@azaroth42  Is the solution posted in my above comment is ok for works?

**Comment by azaroth42** [comment]
True enough! And yes, it's only one additional hop, so expense wise it shouldn't be too terrible ... especially if the unit is only used to disambiguate the small number of conflicts across systems

**Comment by clarkepeterf** [comment]
Awesome, I will move forward with that then - thank you!

**Comment by clarkepeterf** [comment]
Unfortunately I'm getting some timeouts for the work queries:

https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22_stemmed%22%3Afalse%2C%22_lang%22%3A%22en%22%2C%22identifier%22%3A%22ils%3Ayul%3A5112994%22%7D%2C%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500303563%22%7D%7D%7D%7D%7D%5D%7D

May need to modify the query or search for optimizations similar to https://github.com/project-lux/lux-marklogic/issues/304

**Comment by clarkepeterf** [comment]
@azaroth42 correct - going through the objects is a fallback. But was just testing with a known identifier. So other queries that go disambiguate through Objects will likely also time out.

Just checked the data though and looks like there are not any duplicate "ils:yul:" identifiers for Works, so disambiguating through Objects may never be necessary :)

**Comment by brent-hartwig** [comment]
@clarkepeterf, I see I'm late to this show but the implementation strikes me as "alternative ID".  Must the provided ID always match a `content` property's entire value?  If yes, the middle tier could invoke a search such as `{ "alternativeId": "B2021.5" }` and the new search terms (one per supported scope) could be configured similar to the `recordType` search terms, which use the `propertyValue` search pattern.  If more than one could be returned and thus more criteria is required, a new search pattern could be implemented.  For instance, would requiring a sibling property of `"type": "Identifier"` be sufficient?  There's a way to pull that off and/or conditionally implement the equivalent of `getSecondaryResolveQuery` within a new search pattern, thereby avoiding a potential second search.  But, let me stop there as I could be off base or the current solution is A-OK.  Thanks.

**Comment by brent-hartwig** [comment]
Gotcha.  I didn't see the explicit use of the `identifier` search term in `handleResolve`.  

> Sometimes units (even the same unit) use the same identifier multiple times. We can disambiguate when a repeated ID is unique within a single unit.

OK, so in lieu of identifying a different way to differentiate, our only means may be how we access the triple store.  What about a post-filter versus repeating the first search with additional criteria?  I have to imagine an ID search isn't going to return more than a handful of documents.  When greater than one, perhaps we can feed those into a more targeted who-is-my-unit query?  [This #49 comment](https://github.com/project-lux/lux-marklogic/issues/49#issuecomment-2338812360) also speaks to a couple other ways to access the triple store.

**Comment by clarkepeterf** [comment]
@brent-hartwig Yeah, I think a post-filter would be an optimization

**Comment by roamye** [comment]
Approved by UAT 9/12
