### ISSUE TITLE
Add endpoint to get ML Version Info

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-middletier#94]
**Problem Description:**
To support https://github.com/project-lux/lux-marklogic/issues/264 we need an endpoint to get version info from ML

**Expected Behavior/Solution:**
Create an endpoint to get version info from ML 
**Requirements:**

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- Same as https://github.com/project-lux/lux-marklogic/issues/264
- https://tman-api-tst.collections.yale.edu/lux-env

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
- Blocking: To support https://github.com/project-lux/lux-marklogic/issues/264

~~**Related Github Issues:**~~

~~- Issues that contain similar work but are not blocking or being blocked by the current issue.~~

~~**Related links:**~~

~~- These links can consist of resources, bugherds, etc.~~

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
Unreviewable? @clarkepeterf or are there example endpoints that can be added to the UAT?

**Comment by clarkepeterf** [comment]
@roamye this supports [#264](https://github.com/project-lux/lux-marklogic/issues/264), so I think that should be used as UAT

**Comment by roamye** [comment]
Approved by UAT 9/27

**Comment by roamye** [comment]
Closing as this was implemented to support ML264 which is now available.
